language: rust
sudo: required
rust:
  - stable
os:
  - linux
dist: xenial

matrix:
  include:
    - name: 'Desktop build'
      addons:
        apt:
          packages:
            - libasound2-plugins
            - libfaad2
            - libfftw3-single3
            - libjack-jackd2-0
            - libmms0
            - libmpg123-0
            - libopus0
            - liborc-0.4-0
            - libpulsedsp
            - libsamplerate0
            - libspeexdsp1
            - libtdb1
            - libtheora0
            - libtwolame0
            - libwayland-egl1-mesa
            - libwebp5
            - libwebrtc-audio-processing-0
            - liborc-0.4-dev
            - pulseaudio
            - pulseaudio-utils

      before_install:
        - curl -L https://servo-deps-2.s3.amazonaws.com/gstreamer/gstreamer-1.16-x86_64-linux-gnu.20190515.tar.gz | tar xz
        - sed -i "s;prefix=/opt/gst;prefix=$PWD/gst;g" $PWD/gst/lib/pkgconfig/*.pc
        - export PKG_CONFIG_PATH=$PWD/gst/lib/pkgconfig
        - export GST_PLUGIN_SYSTEM_PATH=$PWD/gst/lib/gstreamer-1.0
        - export GST_PLUGIN_SCANNER=$PWD/gst/libexec/gstreamer-1.0/gst-plugin-scanner
        - export PATH=$PATH:$PWD/gst/bin
        - export LD_LIBRARY_PATH=$PWD/gst/lib:$LD_LIBRARY_PATH

      before_script:
        - pulseaudio --start
        - gst-inspect-1.0 | grep Total

      script:
        - cargo build
        - ls examples/*.rs | xargs -I{} basename  {} .rs  | grep -v params_connect | RUST_BACKTRACE=1 GST_DEBUG=3 xargs -I{} cargo ex {} --all-features
